-- MySQL Script generated by MySQL Workbench
-- Sun Mar  8 17:18:15 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_puskesmas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_puskesmas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_puskesmas` DEFAULT CHARACTER SET utf8 ;
USE `db_puskesmas` ;

-- -----------------------------------------------------
-- Table `db_puskesmas`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'resepsionis', 'dokter', 'apoteker') NOT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `idusers_UNIQUE` (`idusers` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_puskesmas`.`pasien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`pasien` (
  `idpasien` INT NOT NULL AUTO_INCREMENT,
  `nik` VARCHAR(16) NOT NULL,
  `nama_pasien` VARCHAR(100) NOT NULL,
  `tgl_lahir` DATE NOT NULL,
  `jenis_kelamin` ENUM('L', 'P') NOT NULL,
  `alamat` TEXT(200) NOT NULL,
  `no_telpon` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idpasien`),
  UNIQUE INDEX `nik_UNIQUE` (`nik` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_puskesmas`.`poli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`poli` (
  `id_poli` INT NOT NULL AUTO_INCREMENT,
  `nama_poli` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_poli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_puskesmas`.`dokter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`dokter` (
  `id_dokter` INT NOT NULL AUTO_INCREMENT,
  `nama_dokter` VARCHAR(100) NOT NULL,
  `jadwal_praktik` VARCHAR(100) NOT NULL,
  `users_idusers` INT NOT NULL,
  `poli_id_poli` INT NOT NULL,
  PRIMARY KEY (`id_dokter`),
  INDEX `fk_dokter_users_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_dokter_poli1_idx` (`poli_id_poli` ASC) VISIBLE,
  CONSTRAINT `fk_dokter_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `db_puskesmas`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dokter_poli1`
    FOREIGN KEY (`poli_id_poli`)
    REFERENCES `db_puskesmas`.`poli` (`id_poli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_puskesmas`.`rekam_medis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`rekam_medis` (
  `id_rm` INT NOT NULL AUTO_INCREMENT,
  `tgl_periksa` DATETIME NOT NULL,
  `keluhan` TEXT(2000) NOT NULL,
  `tinggi_badan` INT NOT NULL,
  `berat_bedan` INT NULL,
  `tekanan_darah` VARCHAR(20) NULL,
  `diagnosa` TEXT(2000) NULL,
  `pasien_idpasien` INT NOT NULL,
  `dokter_id_dokter` INT NOT NULL,
  PRIMARY KEY (`id_rm`),
  INDEX `fk_rekam_medis_pasien1_idx` (`pasien_idpasien` ASC) VISIBLE,
  INDEX `fk_rekam_medis_dokter1_idx` (`dokter_id_dokter` ASC) VISIBLE,
  CONSTRAINT `fk_rekam_medis_pasien1`
    FOREIGN KEY (`pasien_idpasien`)
    REFERENCES `db_puskesmas`.`pasien` (`idpasien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rekam_medis_dokter1`
    FOREIGN KEY (`dokter_id_dokter`)
    REFERENCES `db_puskesmas`.`dokter` (`id_dokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_puskesmas`.`obat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`obat` (
  `id_obat` INT NOT NULL AUTO_INCREMENT,
  `nama_obat` VARCHAR(100) NOT NULL,
  `kategori` VARCHAR(50) NOT NULL,
  `stok` INT NOT NULL,
  `satuan` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_obat`),
  UNIQUE INDEX `nama obat_UNIQUE` (`nama_obat` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_puskesmas`.`resep_obat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`resep_obat` (
  `id_resep` INT NOT NULL AUTO_INCREMENT,
  `tgl_resep` DATETIME NOT NULL,
  `status_tebus` ENUM('belum', 'selesai') NOT NULL,
  `rekam_medis_id_rm` INT NOT NULL,
  PRIMARY KEY (`id_resep`),
  INDEX `fk_resep_obat_rekam_medis1_idx` (`rekam_medis_id_rm` ASC) VISIBLE,
  CONSTRAINT `fk_resep_obat_rekam_medis1`
    FOREIGN KEY (`rekam_medis_id_rm`)
    REFERENCES `db_puskesmas`.`rekam_medis` (`id_rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_puskesmas`.`detail_resep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`detail_resep` (
  `id_detail` INT NOT NULL AUTO_INCREMENT,
  `jumlah_obat` INT NOT NULL,
  `dosis` VARCHAR(50) NOT NULL,
  `resep_obat_id_resep` INT NOT NULL,
  `obat_id_obat` INT NOT NULL,
  PRIMARY KEY (`id_detail`),
  INDEX `fk_detail_resep_resep_obat1_idx` (`resep_obat_id_resep` ASC) VISIBLE,
  INDEX `fk_detail_resep_obat1_idx` (`obat_id_obat` ASC) VISIBLE,
  CONSTRAINT `fk_detail_resep_resep_obat1`
    FOREIGN KEY (`resep_obat_id_resep`)
    REFERENCES `db_puskesmas`.`resep_obat` (`id_resep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_resep_obat1`
    FOREIGN KEY (`obat_id_obat`)
    REFERENCES `db_puskesmas`.`obat` (`id_obat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_puskesmas`.`antrean`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_puskesmas`.`antrean` (
  `idantrean` INT NOT NULL AUTO_INCREMENT,
  `tgl_antrean` DATE NOT NULL,
  `no_antrean` INT NOT NULL,
  `status` ENUM('menunggu', 'diperiksa', 'selesai') NOT NULL,
  `pasien_idpasien` INT NOT NULL,
  `poli_id_poli` INT NOT NULL,
  PRIMARY KEY (`idantrean`),
  INDEX `fk_antrean_pasien1_idx` (`pasien_idpasien` ASC) VISIBLE,
  INDEX `fk_antrean_poli1_idx` (`poli_id_poli` ASC) VISIBLE,
  CONSTRAINT `fk_antrean_pasien1`
    FOREIGN KEY (`pasien_idpasien`)
    REFERENCES `db_puskesmas`.`pasien` (`idpasien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_antrean_poli1`
    FOREIGN KEY (`poli_id_poli`)
    REFERENCES `db_puskesmas`.`poli` (`id_poli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
